### PR TITLE
Adds ability to specify a fallthrough

### PR DESCRIPTION
**Pull request by ianepperson**
In order to handle fallthrough, reworked the logic a bit to only store the functions that are intended to be called.

### CODE REVIEW

**Comment by ianepperson** [comment]
This change adds a `fallthrough` option to the case statements.
```
with switch(val) as s:
    s.case('a', process_a, fallthrough=True)
    s.case('b', lambda: process_with_data(val, num, 'other values still'))
    s.default(process_any)
```
Will run both `process_a` and `process_with_data(...)` when `val` is `a`.

**Comment by mikeckennedy** [comment]
Hi, I can't get to this right away. Today and tomorrow are flat-out. But I will and thank you for submitting it.

**Comment by mikeckennedy** [comment]
Thanks @ianepperson This is nice work and clever use of recursion. I'm adding a few more unit tests to support the variations here. Hold tight for that.

**Comment by ianepperson** [comment]
Thanks @mikeckennedy .  The return value may be useful for other logic as well.

**Comment by mikeckennedy** [comment]
Indeed, and here is the commit for some more tests (and a little docs mixed in): https://github.com/mikeckennedy/python-switch/commit/00194fb1412e37f7637f5c3a9eef48c18367a9ca

**Pull request merged**
